apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - temp.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /kind
        value: Rollout

      - op: replace
        path: /apiVersion
        value: argoproj.io/v1alpha1
      
      - op: add
        path: /spec/strategy
        value:
          blueGreen: 
            activeService: rollout-bluegreen-active
            previewService: rollout-bluegreen-preview
            autoPromotionEnabled: true
 